// app/web/src/shared/ui/button.tsx
import { Button as BaseButton } from "@base-ui/react/button";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "@/shared/lib/utils";
import type { ComponentProps } from "react";

export const buttonVariants = cva(
  "inline-flex min-h-11 items-center justify-center gap-2 rounded-full px-5 text-sm font-semibold transition-[color,background-color,border-color,box-shadow] duration-200 ease-out focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--ring)] disabled:pointer-events-none disabled:opacity-45",
  {
    defaultVariants: { size: "default", variant: "default" },
    variants: {
      size: { default: "h-11", sm: "h-9 px-4 text-xs", icon: "size-11 px-0" },
      variant: {
        default: "bg-[var(--primary)] text-white hover:bg-[var(--primary-hover)]",
        outline:
          "border border-[var(--line-strong)] bg-[var(--surface)] text-[var(--foreground)] hover:border-[var(--interactive-blue)] hover:bg-[var(--interactive-blue-soft)] hover:text-[var(--interactive-blue-ink)]",
        ghost:
          "text-[var(--foreground)] hover:bg-[var(--interactive-blue-soft)] hover:text-[var(--interactive-blue-ink)]",
        destructive: "bg-[var(--destructive)] text-white hover:bg-[var(--destructive-hover)]",
      },
    },
  },
);
export function Button({
  className,
  size,
  variant,
  ...props
}: ComponentProps<typeof BaseButton> & VariantProps<typeof buttonVariants>) {
  return <BaseButton className={cn(buttonVariants({ size, variant }), className)} {...props} />;
}

// lp/src/lib/components/ui/Button.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  type Variant = "primary" | "outline" | "quiet";
  type Size = "sm" | "md" | "lg";

  type ButtonProps = {
    href?: string;
    variant?: Variant;
    size?: Size;
    class?: string;
    children: Snippet;
  };

  let {
    href,
    variant = "primary",
    size = "md",
    class: className = "",
    children,
  }: ButtonProps = $props();

  const base =
    "group inline-flex items-center justify-center gap-3 rounded-full border font-medium tracking-[-0.01em] transition duration-300 ease-fluid focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-brand-purple";
  const variants: Record<Variant, string> = {
    primary:
      "border-transparent bg-night text-white hover:-translate-y-0.5 hover:bg-brand-red",
    outline:
      "border-current/25 bg-transparent text-current hover:-translate-y-0.5 hover:border-brand-purple hover:text-brand-purple",
    quiet:
      "border-transparent bg-transparent px-0 text-current hover:text-brand-purple",
  };
  const sizes: Record<Size, string> = {
    sm: "px-4 py-2 text-xs",
    md: "px-5 py-3 text-sm",
    lg: "px-7 py-4 text-sm",
  };
  const classes = $derived(`${base} ${variants[variant]} ${sizes[size]} ${className}`);
</script>

{#if href}
  <a class={classes} href={href}>
    {@render children()}
  </a>
{:else}
  <button class={classes} type="button">
    {@render children()}
  </button>
{/if}
