// lp/src/lib/components/ui/Button.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  type Variant = "primary" | "accent" | "outline" | "quiet";
  type Size = "sm" | "md" | "lg";

  type ButtonProps = {
    children: Snippet;
    class?: string;
    href?: string;
    size?: Size;
    variant?: Variant;
  };

  let {
    children,
    class: className = "",
    href,
    size = "md",
    variant = "primary",
  }: ButtonProps = $props();

  const base =
    "group inline-flex items-center justify-center gap-3 rounded-full border font-medium tracking-[-0.01em] transition duration-300 ease-fluid focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-brand-purple";
  const variants: Record<Variant, string> = {
    accent:
      "border-transparent bg-brand-red text-white hover:-translate-y-0.5 hover:bg-brand-red",
    outline:
      "border-current/25 bg-transparent text-current hover:-translate-y-0.5 hover:border-brand-purple hover:text-brand-purple",
    primary:
      "border-transparent bg-night text-white hover:-translate-y-0.5 hover:bg-brand-red",
    quiet:
      "border-transparent bg-transparent px-0 text-current hover:text-brand-purple",
  };
  const sizes: Record<Size, string> = {
    lg: "px-7 py-4 text-sm",
    md: "px-5 py-3 text-sm",
    sm: "px-4 py-2 text-xs",
  };
  const classes = $derived(`${base} ${variants[variant]} ${sizes[size]} ${className}`);
</script>

{#if href}
  <a class={classes} href={href}>
    {@render children()}
  </a>
{:else}
  <button class={classes} type="button">
    {@render children()}
  </button>
{/if}

// app/web/src/components/ui/button.tsx
import { Button as BaseButton } from "@base-ui/react/button";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "../../lib/utils";
import type { ComponentProps } from "react";

export const buttonVariants = cva(
  "inline-flex min-h-9 items-center justify-center gap-2 rounded-md px-3 text-sm font-semibold transition-colors focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--ring)] disabled:pointer-events-none disabled:opacity-45",
  {
    variants: {
      variant: {
        default:
          "bg-[var(--primary)] text-[var(--primary-foreground)] hover:bg-[var(--primary-hover)]",
        outline: "border border-[var(--border)] bg-transparent hover:bg-[var(--accent)]",
        ghost: "hover:bg-[var(--accent)]",
        destructive: "bg-[var(--destructive)] text-white hover:opacity-90",
      },
      size: { default: "h-9", sm: "h-8 px-2 text-xs", icon: "size-9 px-0" },
    },
    defaultVariants: { variant: "default", size: "default" },
  },
);
export function Button({
  className,
  variant,
  size,
  ...props
}: ComponentProps<typeof BaseButton> & VariantProps<typeof buttonVariants>) {
  return <BaseButton className={cn(buttonVariants({ variant, size }), className)} {...props} />;
}
